flaskblog/categories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class CategoryForm(FlaskForm):
    name = StringField('Category Name', validators=[DataRequired()])
    sequence = IntegerField('Sequence')
    submit = SubmitField('Create')

flaskblog/categories/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flaskblog import db
from flaskblog.models import Category, Post
from flaskblog.categories.forms import CategoryForm
from flask_login import login_required, current_user


categories = Blueprint('categories', __name__)


@categories.route("/category/new", methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        flash('Category Created!', 'success')
        category = Category(name=form.name.data, sequence=form.sequence.data)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('categories/create_category.html', title='New Category', form=form, legend='New Category')


@categories.route("/category/<int:category_id>")
def category(category_id):
    is_login = current_user.is_authenticated

    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(category_id=category.id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('categories/category.html', title=category.name, category=category, posts=posts, is_login=is_login)


@categories.route("/category/<int:category_id>/update", methods=['GET', 'POST'])
@login_required
def update_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        category.sequence = form.sequence.data
        db.session.commit()
        flash('Category info updated', 'success')
        return redirect(url_for('categories.category', category_id=category.id))
    elif request.method == 'GET':
        form.name.data = category.name
        form.sequence.data = category.sequence
    return render_template('categories/create_category.html', title='Update Category', form=form, legend='Update Category')


@categories.route("/category/<int:category_id>/delete", methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash('Category Deleted', 'success')
    return redirect(url_for('main.home'))


@categories.route("/categories/")
def category_list():
    categories = Category.query.order_by(Category.sequence.asc())
    return render_template('categories/category_list.html', title='Categories', categories=categories)

flaskblog/main/routes.py
from flask import render_template, request, redirect, Blueprint, url_for
from flaskblog.models import Post, Category, AccessCount
from flask_login import current_user
from flaskblog.main.utils import update_and_init_access_count

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    update_and_init_access_count()
    return render_template('main/home.html', posts=posts)


@main.route("/about")
def about():
    return render_template('main/about.html', title='About')


@main.route("/future_feature")
def future_feature():
    return render_template('main/future_feature.html', title='待完成的功能')


@main.route("/search", methods=['GET', 'POST'])
def search():
    keyword = request.args.get('keyword')
    page = request.args.get('page', 1, type=int)

    if not keyword:
        return redirect(url_for('main.home'))

    posts = Post.query.filter(Post.title.contains(keyword)).order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    post_count = Post.query.filter(Post.title.contains(keyword)).count()  # If switch to postgres then stop using this

    return render_template('main/search.html', posts=posts, keyword=keyword, post_count=post_count, page=page)


@main.app_context_processor
def context_processor():
    categories_sorted_by_sequence = Category.query.order_by(Category.sequence.desc()).all()
    categories_sorted_by_id = Category.query.order_by(Category.id.asc()).all()
    recent_posts = Post.query.order_by(Post.id.desc()).limit(3).all()
    access_count = AccessCount.query.first().count
    return {
        'categories_sorted_by_sequence': categories_sorted_by_sequence,
        'categories_sorted_by_id': categories_sorted_by_id,
        'current_user': current_user,
        'recent_posts': recent_posts,
        'access_count': access_count,
        'site_url': request.base_url
    }

flaskblog/posts/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flaskblog import db
from flaskblog.models import Post, Category
from flaskblog.posts.forms import PostForm
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    form.category_id.choices = [(category.id, category.name) for category in Category.query.all()]
    if form.validate_on_submit():
        flash('Post Created!', 'success')
        post = Post(
            title=form.title.data,
            content=form.content.data,
            author=current_user,
            category_id=form.category_id.data
        )
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('posts/create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    if not current_user.is_authenticated:
        post.click_count += 1
        db.session.commit()
    return render_template('posts/post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    form.category_id.choices = [(category.id, category.name) for category in Category.query.all()]

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.category_id = form.category_id.data
        db.session.commit()
        flash('Post updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('posts/create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post Deleted', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, abort
from flaskblog import db, bcrypt
from flaskblog.models import User
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import send_reset_email
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if User.query.all():
        return abort(404)
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('users/login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():

        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account information updated!', 'success')
        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('users/account.html', title='Account', form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
        flash('If the email exist, you will receive a confirmation email soon.', 'info')
        return redirect(url_for('users.login'))

    return render_template('users/reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<string:token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('Invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f'Password updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('users/reset_token.html', title='Reset Password', form=form)

flaskblog/templates/articles.html
{% macro display_articles(posts, category, categories_sorted_by_id, current_user) %}
    {% for post in posts.items %}
    <article class="card">
        <div>
            <a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a><br>
            <small class="text-muted">
                Post at：{{ post.date_posted.strftime('%d-%m-%Y') }} &nbsp;&nbsp;&nbsp;
                Category： <a href="{{ url_for('categories.category', category_id=post.category_id) }}">{{ categories_sorted_by_id[post.category_id - 1] }}</a>&nbsp;&nbsp;&nbsp;
                Clicks： {{ post.click_count }}
            </small>
            <p class="article-content">{{ post.content|truncate|markdown }}
                <a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-outline-secondary btn-sm">Read More</a>
            </p>
        </div>
    </article>
    {% endfor %}
{% endmacro %}

flaskblog/templates/category.html
{% extends "layout.html" %}
{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Category?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('categories.delete_category', category_id=category.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

<!---->
<h1 class="mb-3">分类：{{ category.name }}</h1>
{% if is_login %}
    <small class="font-weight-bold">Post count: {{ posts.total }}</small><br>
    <small class="font-weight-bold">Sequence: {{ category.sequence }}</small>
    <div class="media-body">

    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('categories.update_category', category_id=category.id) }}">Update</a>
    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
    </div>
{% endif %}

    {% for post in posts.items %}
        <article class="media content-section">
          <div class="media-body">
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
              <small class="text-muted">
                发布于：{{ post.date_posted.strftime('%d-%m-%Y') }} &nbsp;&nbsp;&nbsp;
                分类于： <a href="{{ url_for('categories.category', category_id=post.category_id) }}">{{ categories_sorted_by_id[post.category_id - 1] }}</a>&nbsp;&nbsp;&nbsp;
                点击数： {{ post.click_count }}
              </small><br><br>
            <p class="article-content">{{ post.content|markdown|truncate }}
                <br><br><a href="{{ url_for('posts.post', post_id=post.id) }}" class="btn btn-outline-secondary btn-sm">Read More</a>
            </p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-dark mb-4" href="{{ url_for('categories.category', category_id=category.id, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-light mb-4" href="{{ url_for('categories.category',category_id=category.id, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
         <title>David Zheng's Blog</title>
    {% endif %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css">
	<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.3.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.3.2/styles/a11y-dark.min.css">

</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top nav-color-gainsboro">
            <a class="navbar-brand" href="/"><strong>David Zheng's Blog</strong></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('categories.category_list') }}">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    </li>
                </ul>
                 <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% endif %}
                    <form class="form-inline my-2 my-lg-0" action="{{ url_for('main.search') }}">
                      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
                      <button class="btn btn-outline-light my-2 my-sm-0" type="submit">Search Blog</button>
                    </form>
                </div>

            </div>
        </nav>
    </header>

    <div class="content">
        <div class="messages">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        {% block content %}{% endblock %}

        </div>
    </div>
    <div class="sidebar active">
        <button class="sidebar-toggle"><i class="fa fa-bars"></i></button>
        <h3 >Recent Blogs</h3>
        <ul class="list-group">
            {% for post in recent_posts %}
                <li class="list-group-item"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a><br>
                    {{ post.date_posted.strftime('%d-%m-%Y') }}
                </li>
            {% endfor %}
        </ul>

<!--        <div>-->
<!--            <i class="fa fa-desktop fa-2x sidebar-icon"></i>-->
<!--                <h2>{{ access_count }}</h2>-->
<!--            <p class="count-text ">Visitors</p>-->
<!--        </div>-->

        <div class="my-detail">
            <a href="https://www.facebook.com/zhen.zheng.5876/"><img class="sidebar-icon" src="{{ url_for('static', filename='contact_icons/facebook.png') }}"/></a>
            <a href="https://github.com/BuddyLich"><img class="sidebar-icon" src="{{ url_for('static', filename='contact_icons/github.png') }}"/></a>
            <a href="mailto:zhengzhen048@gmail.com"><img class="sidebar-icon" src="{{ url_for('static', filename='contact_icons/gmail.webp') }}"/></a>
        </div>
    </div>

    <script>
        const btn = document.querySelector('.sidebar-toggle');
        const sidebar = document.querySelector('.sidebar')

        btn.addEventListener("click", () => {
            sidebar.classList.toggle('active');
        });

        window.addEventListener('resize', () =>{

            if (document.documentElement.clientWidth < 1540) {
                sidebar.classList.remove('active');
            }
        });
    </script>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</body>
</html>