flaskblog/categories/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.validators import DataRequired


class CategoryForm(FlaskForm):
    name = StringField('Category Name', validators=[DataRequired()])
    sequence = IntegerField('Sequence')
    submit = SubmitField('Create')

flaskblog/categories/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flaskblog import db
from flaskblog.models import Category, Post
from flaskblog.categories.forms import CategoryForm
from flask_login import login_required, current_user


categories = Blueprint('categories', __name__)


@categories.route("/category/new", methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        flash('Category Created!', 'success')
        category = Category(name=form.name.data, sequence=form.sequence.data)
        db.session.add(category)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('categories/create_category.html', title='New Category', form=form, legend='New Category')


@categories.route("/category/<int:category_id>")
def category(category_id):
    is_login = current_user.is_authenticated

    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(category_id=category.id).order_by(Post.date_posted.desc()).paginate(page=page, per_page=10)
    return render_template('categories/category.html', title=category.name, category=category, posts=posts, is_login=is_login)


@categories.route("/category/<int:category_id>/update", methods=['GET', 'POST'])
@login_required
def update_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = CategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        category.sequence = form.sequence.data
        db.session.commit()
        flash('Category info updated', 'success')
        return redirect(url_for('categories.category', category_id=category.id))
    elif request.method == 'GET':
        form.name.data = category.name
        form.sequence.data = category.sequence
    return render_template('categories/create_category.html', title='Update Category', form=form, legend='Update Category')


@categories.route("/category/<int:category_id>/delete", methods=['POST'])
@login_required
def delete_category(category_id):
    category = Category.query.get_or_404(category_id)
    db.session.delete(category)
    db.session.commit()
    flash('Category Deleted', 'success')
    return redirect(url_for('main.home'))


@categories.route("/categories/")
def category_list():
    categories = Category.query.order_by(Category.sequence.asc())
    return render_template('categories/category_list.html', title='Categories', categories=categories)

flaskblog/templates/categories/category.html
{% extends "layout.html" %}
{% from "articles.html" import display_articles %}
{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Category?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('categories.delete_category', category_id=category.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

<!---->

<div class="category-list">
    <ul class="list-group list-group-flush">
        <h2>Category: {{category.name}}</h2>
        {% if is_login %}
            <small>Post count: {{ posts.total }}  Sequence: {{ category.sequence }}</small>
            <div class="media-body">
                <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('categories.update_category', category_id=category.id) }}">Update</a>
                <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
            </div>
        {% endif %}

        {% for post in posts.items %}
        <li class="list-group-item">
            <small>{{ post.date_posted.strftime('%d-%m-%Y') }}</small>
                <a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a>
            <small class="category-post-click">clicks: {{ post.click_count }}</small>
        </li>

    {% endfor %}

    </ul>
</div>
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if posts.page == page_num %}
                <a class="btn btn-dark mb-4" href="{{ url_for('categories.category', category_id=category.id, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-light mb-4" href="{{ url_for('categories.category',category_id=category.id, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/categories/category_list.html
{% extends "layout.html" %}
{% block content %}

        <ul class="list-group category-list">
            <li class="list-group-item">
                <h3>Categories</h3>
            </li>
            {% for category in categories %}
                <li  class="list-group-item">
                    <a href="{{ url_for('categories.category', category_id=category.id) }}">{{ category.name }}</a>
                </li>
            {% endfor %}
            {% if current_user.is_authenticated %}
                <li  class="list-group-item">
                    <strong><a href="{{ url_for('categories.new_category') }}">New Category+</a></strong>
                </li>
            {% endif %}
        </ul>

{% endblock %}

flaskblog/templates/categories/create_category.html
{% extends "layout.html" %}
{% block content %}
 <div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.name.label(class="form-control-label") }}
                {% if form.name.errors %}
                    {{ form.name(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.name(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.sequence.label(class="form-control-label") }}
                {% if form.sequence.errors %}
                    {{ form.sequence(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.sequence.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.sequence(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </fieldset>
    </form>
</div>
{% endblock content %}